---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    server: mc
  name: mc
spec:
  volumeName: mc-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
